---
title: "CLIF_prone_incidence_analysis"
author: "Anna Barker and Chad Hochberg"
date: "`r Sys.Date()`"
output: html_document
---
#This File is Run AFTER the Cohort Identification R Markdown ('cohort_identification_prone_incidence.Rmd')
#Specify File Paths, Project Path and Site - SITE SPECIFIC
#Load the Analytic File
```{r}
tables_location <- '~/workspace/Storage/chochbe1/JH_CCRD/CLIF/rclif'
project_location <- '~/workspace/Storage/chochbe1/JH_CCRD/CLIF/CLIF_Projects/CLIF_prone_incidence'
site <- "Hopkins"
file_type <- 'parquet'
#tables_location <- 'z:/barker/clif_temp'
#project_location <- 'z:/barker/projects/CLIF_prone_incidence'
#site <- "UMich"
```


```{r Load Needed Libraries, include=FALSE}
packages <- c("lubridate", 
              "tidyverse", 
              "dplyr",
              "tableone", 
              "readxl", 
              "arrow", 
              "collapse", 
              "data.table",
              "viridis",
              "sandwich", #Cluster Robust Standard Errors
              "lmtest") #Allows Calculation of Cluster Robust Standard Errors

install_if_missing <- function(package) {
  if (!require(package, character.only = TRUE)) {
    install.packages(package, dependencies = TRUE)
    library(package, character.only = TRUE)
  }
}

sapply(packages, install_if_missing)
rm(packages, install_if_missing)

#Use Dplyr select as default
select <- dplyr::select

#Create Sub Folders for Graphs within Project Output Folder
# Check if the output directory exists; if not, create it
if (!dir.exists(paste0(project_location, "/project_output/graphs"))) {
  dir.create(paste0(project_location, "/project_output/graphs"))
}

```


```{r Load Site-specific analytic data set}
#NOTE: This Table is Created by the 
prone_analytic_df <- open_dataset(paste0(project_location, '/project_tables/prone_analytic_data.parquet')) |>
  collect()
```


#Additional Cleaning of Analytic Dataset
#Includes Finalzing Covariates
```{r Start Times and Whether Pediatric Patients Are Included}
#Further Define sex_category as female 1, male/other/unknown 0
prone_analytic_df <- prone_analytic_df |>
  mutate(female=fifelse(tolower(sex_category)=='female', 1, 0)) |>
  #Define Calendar Time for Time of Enrollment
  mutate(year=year(t_enrollment)) |>
  mutate(calendar_month=month(t_enrollment)) |>
  arrange(year, calendar_month)

#Report Out Minimum and Maximum Times
cat('At', site, 'the first eligible patient was enrolled on', as.character(first(prone_analytic_df$t_enrollment)), 
    '\n and the last on', as.character(last(prone_analytic_df$t_enrollment)))

#Create a Study Month Data Frame to Merge to Create Study Month 1-84; Will Allow This Code to Work on 2024 Data
study_month <- data.frame(start_date=seq(ym("201801"), ym("202412"), by= "months")) |>
  mutate(calendar_month=month(start_date)) |>
  mutate(year=year(start_date)) |>
  arrange(year, calendar_month) |>
  mutate(study_month=seq(1:84)) |>
  select(-start_date) |>
  mutate(study_quarter=ceiling(study_month/3))

#Now Merge to Prone Analytic_DF
prone_analytic_df <- prone_analytic_df |>
  left_join(study_month) 
 
#Define the Pre-Specified Study Periods
#Jan 2018-Feb 2020 'Pre-COVID', March 2020-February 2022 'COVID', March 2022-December 2023 'Post_COVID'
#So that All Sites Can Participate Will use the COVID Period as The Reference
prone_analytic_df <- prone_analytic_df |>
  mutate(study_period=fcase(
    study_month>=1 & study_month<27, 'Pre-COVID',
    study_month>=27 & study_month<51, 'COVID',
    study_month>=51, 'Post-COVID'
  )) |>
  mutate(study_period_cat=factor(study_period,
                               levels = c("COVID", "Pre-COVID", "Post-COVID"),
                               labels = c(1, 2, 3)))

#In this script we keep track of the minimum and maximum study month both for graphs and for the modelling
min_month <- min(prone_analytic_df$study_month)
max_month <- max(prone_analytic_df$study_month)
min_quarter <- min(prone_analytic_df$study_quarter)
max_quarter <- max(prone_analytic_df$study_quarter)

#Create 'site_type' vector that shows Which study periods are Included
site_type <- prone_analytic_df |>
  distinct(study_period) 
site_type <- paste(site_type$study_period, collapse = ",")
#Possible Combinations are "Pre-COVID,COVID,Post-COVID"|"COVID,Post-COVID"|"Pre-COVID,"COVID"

#Keep Track of the Number of Hospitals
n_hospitals <- length(unique(prone_analytic_df$hospital_id[!is.na(prone_analytic_df$hospital_id)]))

#Create a Few More Variables
prone_analytic_df <- prone_analytic_df |>
  mutate(admit_to_enrolled=as.duration(t_enrollment-final_admission_dttm)/dhours(1)) |>
  mutate(ett_to_enrolled=as.duration(t_enrollment-vent_episode_start)/dhours(1)) |>
  mutate(severe_ards=fifelse(min_pf_ratio<100, 1, 0))
```


```{r Describe The Number of Admissions Per Month, Admissions Per Period}
#Create a Table of N of Patients and Number Proned Per Study Month
prone_per_month <- prone_analytic_df |> 
  group_by(study_month) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'year' = mean(year),
    'calendar_month' = mean(calendar_month),
    'study_period' = max(study_period),
    'n_patients' = n(),
    'n_proned_12_hr' = sum(prone_12hour_outcome),
    'proned_12_hr_percent' = mean(prone_12hour_outcome),
    'n_proned' = sum(proned),
    'proned_percent' = mean(proned),
    'standard_error' = sqrt(mean(prone_12hour_outcome) * (1 - mean(prone_12hour_outcome)) / n()),
    'standard_error_alltime' = sqrt(mean(proned) * (1 - mean(proned)) / n())
  ) |>
  relocate(site, n_hospitals, .before = study_month)
write_csv(prone_per_month, paste0(project_location, '/project_output/', site,'_prone_per_month.csv'))

#Create a Table of N of Patients and Number Proned Per Study Month Per Hospital
prone_per_month_by_hospital <- prone_analytic_df |> 
  group_by(study_month, hospital_id) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'year' = mean(year),
    'calendar_month' = mean(calendar_month),
    'study_period' = max(study_period),
    'n_patients' = n(),
    'n_proned_12_hr' = sum(prone_12hour_outcome),
    'proned_12_hr_percent' = mean(prone_12hour_outcome),
    'n_proned' = sum(proned),
    'proned_percent' = mean(proned),
    'standard_error' = sqrt(mean(prone_12hour_outcome) * (1 - mean(prone_12hour_outcome)) / n()),
    'standard_error_alltime' = sqrt(mean(proned) * (1 - mean(proned)) / n())
  ) |>
  relocate(site, n_hospitals, .before = study_month)
write_csv(prone_per_month_by_hospital, paste0(project_location, '/project_output/', site,'_prone_per_month_hospital.csv'))


#Repeat Per Study Period
prone_per_period <- prone_analytic_df |> 
  group_by(study_period) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'n_proned_12_hr' = sum(prone_12hour_outcome),
    'proned_12_hr_percent' = mean(prone_12hour_outcome),
    'n_proned' = sum(proned),
    'proned_percent' = mean(proned),
    'standard_error' = sqrt(mean(prone_12hour_outcome) * (1 - mean(prone_12hour_outcome)) / n()),
    'standard_error_alltime' = sqrt(mean(proned) * (1 - mean(proned)) / n()) 
  ) |>
  relocate(site, n_hospitals, .before = study_period)
write_csv(prone_per_period, paste0(project_location, '/project_output/', site,'_prone_per_period.csv'))

#Repeat Per Study Quarter
prone_per_quarter <- prone_analytic_df |> 
  group_by(study_quarter) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'study_period' = max(study_period),
    'n_patients' = n(),
    'n_proned_12_hr' = sum(prone_12hour_outcome),
    'proned_12_hr_percent' = mean(prone_12hour_outcome),
    'n_proned' = sum(proned),
    'proned_percent' = mean(proned),
    'standard_error' = sqrt(mean(prone_12hour_outcome) * (1 - mean(prone_12hour_outcome)) / n()), 
    'standard_error_alltime' = sqrt(mean(proned) * (1 - mean(proned)) / n()) 
      ) |>
  relocate(site, n_hospitals, .before = study_quarter)
write_csv(prone_per_quarter, paste0(project_location, '/project_output/', site,'_prone_per_quarter.csv'))

#Create a Histogram of Admissions Per Study Month by Hospital
#Create Month Labels - Will Use Study Specific Min and Max Months to Select The Right Grouping
month_labels <- c(
'Jan18', 'Feb18', 'Mar18','Apr18', 
'May18', 'Jun18', 'Jul18', 'Aug18',
'Sep18', 'Oct18', 'Nov18', 'Dec18',
'Jan19', 'Feb19', 'Mar19','Apr19', 
'May19', 'Jun19', 'Jul19', 'Aug19',
'Sep19', 'Oct19', 'Nov19', 'Dec19',
'Jan20', 'Feb20', 'Mar20','Apr20', 
'May20', 'Jun20', 'Jul20', 'Aug20',
'Sep20', 'Oct20', 'Nov20', 'Dec20',
'Jan21', 'Feb21', 'Mar21','Apr21', 
'May21', 'Jun21', 'Jul21', 'Aug21',
'Sep21', 'Oct21', 'Nov21', 'Dec21',
'Jan22', 'Feb22', 'Mar22','Apr22', 
'May22', 'Jun22', 'Jul22', 'Aug22',
'Sep22', 'Oct22', 'Nov22', 'Dec22',
'Jan23', 'Feb23', 'Mar23', 'Apr23', 
'May23', 'Jun23', 'Jul23', 'Aug23', 
'Sep23', 'Oct23', 'Nov23', 'Dec23',
'Jan24', 'Feb24', 'Mar24', 'Apr24', 
'May24', 'Jun24', 'Jul24', 'Aug24', 
'Sep24', 'Oct24', 'Nov24', 'Dec24')

#Select the Relvant Months from This Vector Using the min_month, max_month
site_month_labels <- month_labels[min_month:max_month]
max_monthly_n <- max(prone_per_month$n_patients)

#Plot of Enrollments Per Month
ggplot(prone_analytic_df, aes(x=study_month, fill=hospital_id)) +
  geom_bar(position = 'stack') +
  theme_classic() +
  scale_x_continuous(breaks=seq(min_month, max_month, by=1), limits = c(min_month, max_month),
                     labels = site_month_labels,
                     name = 'Month-Year') +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 4.75)) +
  scale_y_continuous(name = 'Number of Admissions') +
  scale_fill_viridis_d()
ggsave(paste0(site, '_enrollment_per_month.pdf'),
       path = paste0(project_location, '/project_output/graphs/'))

```
```{r Table 1 by Period and By Hospital}
#Variables to Table 1
to_tab <- c(
  'age_at_admission',
  'female',
  'race_ethnicity',
  'bmi',
  'hospital_id',
  'year',
  'study_period',
  'eligible_by_proseva',
  'eligible_by_prone',
  'admit_to_enrolled', 
  'ett_to_enrolled',
  'or_before_enrollment',
  'min_pf_ratio',
  'severe_ards',
  'first_proseva_mode',
  'first_proseva_peep',
  'first_proseva_fio2',
  'max_norepi_equivalent'
)

#Factor Variables
factors_tab <- c(
  'female',
  'race_ethnicity',
  'hospital_id',
  'year',
  'study_period',
  'or_before_enrollment',
  'first_proseva_mode',
  'max_norepi_equivalent',
  'severe_ards',
  'eligible_by_proseva',
  'eligible_by_prone'
)

#First Create Table with Ranges and Additional Statistics Including Numbers of Missing and Min/Max
tab1 <- CreateTableOne(vars = to_tab, data=prone_analytic_df, factorVars = factors_tab)
summary(tab1) #This will be in HTML File
sink(paste0(project_location, '/project_output/', site, '_table1_missing_ranges.doc'))
#Repeat to Create Word File
summary(tab1)
# Stop saving output to the file
sink() 

#Now Create a Traditional Table 1, One Stratified by Period and One Stratified by Hospital
tab1 <- CreateTableOne(vars = to_tab, strata="study_period", data=prone_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
print(tab1)
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)
write.csv(tab1_excel, file=paste0(project_location, '/project_output/', site, '_Table1_by_Period.csv'))
rm(tab1_excel)

#Now Create a Traditional Table 1, One Stratified by Period and One Stratified by Hospital
if (n_hospitals>1) {
tab1 <- CreateTableOne(vars = to_tab, strata="hospital_id", data=prone_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
print(tab1)
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)
} else {
tab1 <- CreateTableOne(vars = to_tab, data=prone_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
print(tab1)
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing)
}
write.csv(tab1_excel, file=paste0(project_location, '/project_output/', site, '_Table1_by_Hospital.csv'))
rm(tab1_excel)

```

```{r Visualize Proning Over Time}
#Graph the Proning Rate by Study Quarter with Error Bars for Standard Error
#Create Labels for Study Quarter
quarter_labels <- c(
'2018:1-3', '2018:4-6', '2018:7-9', '2018:10-12',
'2019:1-3', '2019:4-6', '2019:7-9', '2019:10-12',
'2020:1-3', '2020:4-6', '2020:7-9', '2020:10-12',
'2021:1-3', '2021:4-6', '2021:7-9', '2021:10-12',
'2022:1-3', '2022:4-6', '2022:7-9', '2022:10-12',
'2023:1-3', '2023:4-6', '2023:7-9', '2023:10-12',
'2024:1-3', '2024:4-6', '2024:7-9', '2024:10-12')
study_quarter_labels <- quarter_labels[min_quarter:max_quarter]

base_plot <- ggplot(prone_per_quarter, aes(x=study_quarter, y=proned_12_hr_percent)) +
  geom_errorbar(aes(ymin = proned_12_hr_percent - standard_error, ymax = proned_12_hr_percent + 
                      standard_error), width = 0.1, alpha = 0.5, color = 'grey') +
  geom_point() +
  geom_line() +
  scale_y_continuous(breaks=seq(0,1, by=0.1), 
                     labels = scales::percent, 
                     limits = c(0,1.0),
                     name = 'Proned within 12 Hours of Enrollment') +
  scale_x_continuous(breaks=seq(min_quarter, max_quarter, by=1),
                     labels = study_quarter_labels,
                     limits = c(min_quarter, max_quarter),
                     name = 'Year: Months') +
  theme_classic() + # theme_classic call
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) # custom x-axis text

#Now Add Annotations and Verticle Lines to Plot Based on What Data a Site Has Contributed
if (site_type == "Pre-COVID,COVID,Post-COVID") { #If Site Has Full Study Period (2018-2023)
  extended <- base_plot +
    geom_vline(xintercept = 9.6667, linetype = 2) +
    annotate("text", x=5.667, y=0.95, label = 'Pre COVID-19') +
    geom_vline(xintercept = 17.6667, linetype = 2) +
    annotate("text", x=13.667, y=0.95, label = 'COVID-19') +
    annotate("text", x=21.667, y=0.95, label = 'Post COVID-19') 
} else if (site_type == "COVID,Post-COVID") {
  extended <- base_plot + 
    geom_vline(xintercept = 17.6667, linetype = 2) +
    annotate("text", x=13.667, y=0.95, label = 'COVID-19') +
    annotate("text", x=21.667, y=0.95, label = 'Post COVID-19') 
} else if (site_type == "Pre-COVID,COVID") {
  extended <- base_plot + 
    geom_vline(xintercept = 9.6667, linetype = 2) +
    annotate("text", x=5.667, y=0.95, label = 'Pre COVID-19') +
    annotate("text", x=13.667, y=0.95, label = 'COVID-19') 
} else {
  extended <- base_plot
}
# Display the extended plot
extended
ggsave(paste0(site, '_proning_by_quarter.pdf'),
       path = paste0(project_location, '/project_output/graphs/'))

#Repeat for any proning, regardless of 12h timing "all time"
base_plot_alltime <- ggplot(prone_per_quarter, aes(x=study_quarter, y=proned_percent)) +
  geom_errorbar(aes(ymin = proned_percent - standard_error_alltime, ymax = proned_percent + 
                      standard_error_alltime), width = 0.1, alpha = 0.5, color = 'grey') +
  geom_point() +
  geom_line() +
  scale_y_continuous(breaks=seq(0,1, by=0.1), 
                     labels = scales::percent, 
                     limits = c(0,1.0),
                     name = 'Proned during Admission') +
  scale_x_continuous(breaks=seq(min_quarter, max_quarter, by=1),
                     labels = study_quarter_labels,
                     limits = c(min_quarter, max_quarter),
                     name = 'Year: Months') +
  theme_classic() + # theme_classic call
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) # custom x-axis text

#Now Add Annotations and Verticle Lines to Plot Based on What Data a Site Has Contributed
if (site_type == "Pre-COVID,COVID,Post-COVID") { #If Site Has Full Study Period (2018-2023)
  extended <- base_plot_alltime +
    geom_vline(xintercept = 9.6667, linetype = 2) +
    annotate("text", x=5.667, y=0.95, label = 'Pre COVID-19') +
    geom_vline(xintercept = 17.6667, linetype = 2) +
    annotate("text", x=13.667, y=0.95, label = 'COVID-19') +
    annotate("text", x=21.667, y=0.95, label = 'Post COVID-19') 
} else if (site_type == "COVID,Post-COVID") {
  extended <- base_plot_alltime + 
    geom_vline(xintercept = 17.6667, linetype = 2) +
    annotate("text", x=13.667, y=0.95, label = 'COVID-19') +
    annotate("text", x=21.667, y=0.95, label = 'Post COVID-19') 
} else if (site_type == "Pre-COVID,COVID") {
  extended <- base_plot_alltime + 
    geom_vline(xintercept = 9.6667, linetype = 2) +
    annotate("text", x=5.667, y=0.95, label = 'Pre COVID-19') +
    annotate("text", x=13.667, y=0.95, label = 'COVID-19') 
} else {
  extended <- base_plot_alltime
}
# Display the extended plot
extended
ggsave(paste0(site, '_proning_by_quarter_alltime.pdf'),
       path = paste0(project_location, '/project_output/graphs/'))

#Now Repeat for Month
#Label Every 3rd Month
tool <- seq(min_month, max_month, by=2)
new_month_labels <- site_month_labels[tool]
base_plot <- ggplot(prone_per_month, aes(x=study_month, y=proned_12_hr_percent)) +
  geom_errorbar(aes(ymin = proned_12_hr_percent - standard_error, ymax = proned_12_hr_percent + standard_error), 
                width = 0.1, alpha = 0.5, color = 'grey') +
  geom_point() +
  geom_line() +
  scale_y_continuous(breaks=seq(0,1, by=0.1), 
                     labels = scales::percent, 
                     limits = c(0,1.0),
                     name = 'Proned within 12 Hours of Enrollment') +
  scale_x_continuous(breaks=seq(min_month, max_month, by=2),
                     labels = new_month_labels,
                     limits = c(min_month, max_month),
                     name = 'Month-Year') +
  theme_classic() + # theme_classic call
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) # custom x-axis text

#Now Add Annotations and Verticle Lines to Plot Based on What Data a Site Has Contributed
if (site_type == "Pre-COVID,COVID,Post-COVID") { #If Site Has Full Study Period (2018-2023)
  extended <- base_plot +
    geom_vline(xintercept = 27, linetype = 2) +
    annotate("text", x=15, y=0.95, label = 'Pre COVID-19') +
    geom_vline(xintercept = 51, linetype = 2) +
    annotate("text", x=39, y=0.95, label = 'COVID-19') +
    annotate("text", x=63, y=0.95, label = 'Post COVID-19') 
} else if (site_type == "COVID,Post-COVID") { #Just COVID and Post COVID
  extended <- base_plot + 
    geom_vline(xintercept = 51, linetype = 2) +
    annotate("text", x=39, y=0.95, label = 'COVID-19') +
    annotate("text", x=63, y=0.95, label = 'Post COVID-19') 
} else if (site_type == "Pre-COVID,COVID") { #Just Pre-COVID and COVID
  extended <- base_plot + 
    geom_vline(xintercept = 27, linetype = 2) +
    annotate("text", x=15, y=0.95, label = 'Pre COVID-19') +
    annotate("text", x=39, y=0.95, label = 'COVID-19')
} else {
  extended <- base_plot
}
# Display the extended plot
extended
ggsave(paste0(site, '_proning_by_month.pdf'),
       path = paste0(project_location, '/project_output/graphs/'))

#Repeat for monthly proning, regardless of 12h cutoff "all_time" proning
base_plot_alltime <- ggplot(prone_per_month, aes(x=study_month, y=proned_percent)) +
  geom_errorbar(aes(ymin = proned_percent - standard_error_alltime, ymax = proned_percent + standard_error_alltime), 
                width = 0.1, alpha = 0.5, color = 'grey') +
  geom_point() +
  geom_line() +
  scale_y_continuous(breaks=seq(0,1, by=0.1), 
                     labels = scales::percent, 
                     limits = c(0,1.0),
                     name = 'Proned during Admission') +
  scale_x_continuous(breaks=seq(min_month, max_month, by=2),
                     labels = new_month_labels,
                     limits = c(min_month, max_month),
                     name = 'Month-Year') +
  theme_classic() + # theme_classic call
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) # custom x-axis text

#Now Add Annotations and Verticle Lines to Plot Based on What Data a Site Has Contributed
if (site_type == "Pre-COVID,COVID,Post-COVID") { #If Site Has Full Study Period (2018-2023)
  extended <- base_plot_alltime +
    geom_vline(xintercept = 27, linetype = 2) +
    annotate("text", x=15, y=0.95, label = 'Pre COVID-19') +
    geom_vline(xintercept = 51, linetype = 2) +
    annotate("text", x=39, y=0.95, label = 'COVID-19') +
    annotate("text", x=63, y=0.95, label = 'Post COVID-19') 
} else if (site_type == "COVID,Post-COVID") { #Just COVID and Post COVID
  extended <- base_plot_alltime + 
    geom_vline(xintercept = 51, linetype = 2) +
    annotate("text", x=39, y=0.95, label = 'COVID-19') +
    annotate("text", x=63, y=0.95, label = 'Post COVID-19') 
} else if (site_type == "Pre-COVID,COVID") { #Just Pre-COVID and COVID
  extended <- base_plot_alltime + 
    geom_vline(xintercept = 27, linetype = 2) +
    annotate("text", x=15, y=0.95, label = 'Pre COVID-19') +
    annotate("text", x=39, y=0.95, label = 'COVID-19')
} else {
  extended <- base_plot_alltime
}
# Display the extended plot
extended
ggsave(paste0(site, '_proning_by_month_alltime.pdf'),
       path = paste0(project_location, '/project_output/graphs/'))

```
```{r Proning and Patient Outcomes in Table Form}
to_tab <- c(
  'prone_episodes',
  'first_prone_episode_hours',
  'median_pt_prone_duration',
  'mean_pt_prone_duration',
  'time_to_prone_hrs',
  'in_hosp_death',
  'death_or_hospice'
)

#Factor Variables
factors_tab <- c(
   'prone_12hour_outcome',
  'proned',
  'in_hosp_death',
  'death_or_hospice'
)

#First Create Table with Ranges and Additional Statistics Including Numbers of Missing and Min/Max
tab2 <- CreateTableOne(vars = to_tab, data=prone_analytic_df, factorVars = factors_tab)
summary(tab2) #This will be in HTML File
sink(paste0(project_location, '/project_output/', site, '_table2_missing_ranges.doc'))
#Repeat to Create Word File
summary(tab2)
# Stop saving output to the file
sink() 

#Now Create a Traditional Table 1, One Stratified by Period and One Stratified by Hospital
tab2 <- CreateTableOne(vars = to_tab, strata="study_period", data=prone_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
print(tab2)
tab2_excel <- as.data.frame(print(tab2, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)
write.csv(tab2_excel, file=paste0(project_location, '/project_output/', site, '_Table_Prone_Outcomes_Period.csv'))
rm(tab2_excel)

#Now Create a Traditional Table 1, One Stratified by Period and One Stratified by Hospital
if (n_hospitals>1) {
tab2 <- CreateTableOne(vars = to_tab, strata="hospital_id", data=prone_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
print(tab2)
tab2_excel <- as.data.frame(print(tab2, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)
} else {
tab2 <- CreateTableOne(vars = to_tab, data=prone_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
print(tab2)
tab2_excel <- as.data.frame(print(tab2, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) 
}
write.csv(tab2_excel, file=paste0(project_location, '/project_output/', site, '_Table_Prone_Outcomes_Period.csv'))
rm(tab2_excel)
```

```{r Function to Summarise Logistic Regression Models}
model_summary_table <- function(model) {
 
if (n_hospitals>1) {
  #Cluster Robust Standard Errors Using LM Test
  coef_table <- coeftest(model, vcovCL(model, cluster = prone_analytic_df$hospital_id)) 
  # Cluster-robust covariance matrix
  clustered_se <- vcovCL(model, cluster = prone_analytic_df$hospital_id)
  #Compute confidence intervals manually using the clustered SE
  conf_int <- coefci(model, vcov. = clustered_se)
}  else {
  coef_table <- coeftest(model)
  conf_int <- coefci(model)
}
 model_table <- data.frame(
  'site' = site,
  'n_observations' = nobs(model),
  'term' = rownames(coef_table),
  'estimate' = coef_table[, "Estimate"],
  'std_error' = coef_table[, "Std. Error"],
  'p_value' = coef_table[, "Pr(>|z|)"],
  'odds_ratio' = round(exp(coef_table[, "Estimate"]), 3),  # Exponentiated coefficients as Odds Ratios
  'lower_bound' = exp(conf_int[, 1]),  # Lower bound of CI from coefci()
  'upper_bound' = exp(conf_int[, 2])   # Upper bound of CI from coefci()
)
model_table <- model_table |>
  mutate(confidence_interval=paste0(round(lower_bound, 3), ' - ', round(upper_bound, 3))) |>
  mutate(n_hospitals=n_hospitals) |>
  relocate(confidence_interval, .before = lower_bound) |>
  relocate(n_hospitals, .after = n_observations) 
  rownames(model_table) <- NULL
return(model_table)
}
```


```{r Segmented Regression - Univariable}
#For Sites with > 1 Hospital, Run Models with Fixed Effect for Hospital and Clustered Standard Errors 
#For now these are Logistic Regressions
#This is the Model Form for Evaluating the Step Changes NOT taking Into Account Time Trends
#First look at primary outcome proning within 12 hours. Then look at all proning. 
if (n_hospitals>1) {
model_form_step <- prone_12hour_outcome ~ study_period + factor(hospital_id)
unvar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
} else {
model_form_step <- prone_12hour_outcome ~ study_period
unvar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
}

summary(unvar_mod)
unvar_mod_summary <- model_summary_table(unvar_mod)

#This is the Model Form for Evaluating the Step Changes AND Time Trends
#Will Scale STudy Month So Coefficients Tell Us About Change in Log Odds Per 3 month Change
prone_analytic_df <- prone_analytic_df |>
  mutate(month_scaled=study_month/3)

if (n_hospitals>1) {
model_form_step <- prone_12hour_outcome ~ study_period + study_period:month_scaled + factor(hospital_id)
unvar_mod_interact <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
} else {
model_form_step <- prone_12hour_outcome ~ study_period + study_period:month_scaled 
unvar_mod_interact <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
}

summary(unvar_mod_interact)
unvar_modinteract_summary <- model_summary_table(unvar_mod_interact)

univar_table <- rowbind(unvar_mod_summary, data.frame('site'=c('','Model With Interaction Terms')), fill = TRUE) |>
               rbind(unvar_modinteract_summary)
# Write the table to a CSV file
write.csv(univar_table, paste0(project_location, '/project_output/', site, '_unadjusted_models.csv'))
```


```{r Adjusted Segmented Regression}
if (n_hospitals>1) {
model_form_step <- prone_12hour_outcome ~ study_period + age_at_admission  + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio + factor(hospital_id)
} else {
  model_form_step <- prone_12hour_outcome ~ study_period + age_at_admission  + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio
}

multivar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(multivar_mod)
multivar_mod_summary <- model_summary_table(multivar_mod)

#This is the Model Form for Evaluating the Step Changes AND Time Trends
#Will Scale STudy Month So Coefficients Tell Us About Change in Log Odds Per 3 month Change
if (n_hospitals>1) {
model_form_step <- prone_12hour_outcome ~ study_period + study_period:month_scaled + age_at_admission + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio + factor(hospital_id) 
} else {
  model_form_step <- prone_12hour_outcome ~ study_period + study_period:month_scaled + age_at_admission + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio
}

multivar_mod_interact <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(multivar_mod_interact)
multivar_modinteract_summary <- model_summary_table(multivar_mod_interact)

multivar_table <- rowbind(multivar_mod_summary, data.frame('site'=c('','Model With Interaction Terms')), fill = TRUE) |>
               rbind(multivar_modinteract_summary)
# Write the table to a CSV file
write.csv(multivar_table, paste0(project_location, '/project_output/', site, '_adjusted_models.csv'))
```


```{r Post HOC Analysis Analyzing Just Step Change at Transition to COVID Period With Rate of Change Prior and After}
#For Sites with PRE-COVID Data They Will A STep Change From Pre-COVID to COVID and then analyze effect of time (in 3 month interval before and after this step change)
#For Sites without Pre-COVID Data There is No Period Change and the Interest is in the Rate of Proning Decline Over the Study Period
prone_analytic_df <- prone_analytic_df |>
   mutate(covid_period=fcase(
    study_month>=1 & study_month<27, 'Pre-COVID',
    study_month>=27, 'COVID'
  )) 

#Only Sites with Pre-COVID Data Can Run this Analysis
if (grepl('Pre-COVID', site_type)) {
#First Univariable
if (n_hospitals>1) {
  model_form_step <- prone_12hour_outcome ~ covid_period + covid_period:month_scaled + factor(hospital_id)
} else {
  model_form_step <- prone_12hour_outcome ~ covid_period + covid_period:month_scaled
}
two_period_unvar <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(two_period_unvar)
two_period_unvar_sum <- model_summary_table(two_period_unvar)

if (n_hospitals>1) {
  model_form_step <- prone_12hour_outcome ~ covid_period + covid_period:month_scaled + age_at_admission+ bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio + factor(hospital_id)
} else {
model_form_step <- prone_12hour_outcome ~ covid_period + covid_period:month_scaled + age_at_admission+ bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio 
}

two_period_multivar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(two_period_multivar_mod)
two_period_multivar_sum <- model_summary_table(two_period_multivar_mod)

two_period_table <- rowbind(two_period_unvar_sum, data.frame('site'=c('','Adjusted Model')), fill = TRUE) |>
               rbind(two_period_multivar_sum)
# Write the table to a CSV file
write.csv(two_period_table, paste0(project_location, '/project_output/', site, 'two_period_models.csv'))


} else { 
#First Univariable
if (n_hospitals>1) {
model_form_step <- prone_12hour_outcome ~ month_scaled + factor(hospital_id)
} else {
  model_form_step <- prone_12hour_outcome ~ month_scaled
}
two_period_unvar <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(two_period_unvar)
two_period_unvar_sum <- model_summary_table(two_period_unvar)

#Now Multivariable
if (n_hospitals>1) {
model_form_step <- prone_12hour_outcome ~ month_scaled + age_at_admission  + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio + factor(hospital_id)
} else {
  model_form_step <- prone_12hour_outcome ~ month_scaled + age_at_admission  + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio
}
two_period_multivar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(two_period_multivar_mod)
two_period_multivar_sum <- model_summary_table(two_period_multivar_mod)

two_period_table <- rowbind(two_period_unvar_sum, data.frame('site'=c('','Adjusted Model')), fill = TRUE) |>
               rbind(two_period_multivar_sum)
# Write the table to a CSV file
write.csv(two_period_table, paste0(project_location, '/project_output/', site, 'two_period_models.csv'))
  }
```

```{r Segmented Regression - Univariable - All Proning}
#For Sites with > 1 Hospital, Run Mixed Effects Models Otherwise Run as Logistic Regression
#For now these are Logistic Regressions
#This is the Model Form for Evaluating the Step Changes NOT taking Into Account Time Trends
#Look at all proning outcome. 
if (n_hospitals>1) {
model_form_step <- proned ~ study_period + factor(hospital_id)
unvar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
} else {
model_form_step <- proned ~ study_period
unvar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
}

summary(unvar_mod)
unvar_mod_summary <- model_summary_table(unvar_mod)

#This is the Model Form for Evaluating the Step Changes AND Time Trends
#Will Scale STudy Month So Coefficients Tell Us About Change in Log Odds Per 3 month Change
prone_analytic_df <- prone_analytic_df |>
  mutate(month_scaled=study_month/3)

if (n_hospitals>1) {
model_form_step <- proned ~ study_period + study_period:month_scaled + factor(hospital_id)
unvar_mod_interact <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
} else {
model_form_step <- proned ~ study_period + study_period:month_scaled 
unvar_mod_interact <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
}

summary(unvar_mod_interact)
unvar_modinteract_summary <- model_summary_table(unvar_mod_interact)

univar_table <- rowbind(unvar_mod_summary, data.frame('site'=c('','Model With Interaction Terms')), fill = TRUE) |>
               rbind(unvar_modinteract_summary)
# Write the table to a CSV file
write.csv(univar_table, paste0(project_location, '/project_output/', site, '_unadjusted_models_alltime.csv'))
```



```{r Adjusted Segmented Regression - All Proning}
if (n_hospitals>1) {
model_form_step <- proned ~ study_period + age_at_admission  + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio + factor(hospital_id)
} else {
  model_form_step <- proned ~ study_period + age_at_admission  + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio
}

multivar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(multivar_mod)
multivar_mod_summary <- model_summary_table(multivar_mod)

#This is the Model Form for Evaluating the Step Changes AND Time Trends
#Will Scale STudy Month So Coefficients Tell Us About Change in Log Odds Per 3 month Change
if (n_hospitals>1) {
model_form_step <- proned ~ study_period + study_period:month_scaled + age_at_admission + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio + factor(hospital_id) 
} else {
  model_form_step <- proned ~ study_period + study_period:month_scaled + age_at_admission + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio
}

multivar_mod_interact <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(multivar_mod_interact)
multivar_modinteract_summary <- model_summary_table(multivar_mod_interact)

multivar_table <- rowbind(multivar_mod_summary, data.frame('site'=c('','Model With Interaction Terms')), fill = TRUE) |>
               rbind(multivar_modinteract_summary)
# Write the table to a CSV file
write.csv(multivar_table, paste0(project_location, '/project_output/', site, '_adjusted_models_alltime.csv'))

```


```{r Post HOC Analysis Analyzing Just Step Change at Transition to COVID Period With Rate of Change Prior and After - All proning}
#For Sites with PRE-COVID Data They Will A STep Change From Pre-COVID to COVID and then analyze effect of time (in 3 month interval before and after this step change)
#For Sites without Pre-COVID Data There is No Period Change and the Interest is in the Rate of Proning Decline Over the Study Period
#All prones 
prone_analytic_df <- prone_analytic_df |>
   mutate(covid_period=fcase(
    study_month>=1 & study_month<27, 'Pre-COVID',
    study_month>=27, 'COVID'
  )) 

#Only Sites with Pre-COVID Data Can Run this Analysis
if (grepl('Pre-COVID', site_type)) {
#First Univariable
if (n_hospitals>1) {
  model_form_step <- proned ~ covid_period + covid_period:month_scaled + factor(hospital_id)
} else {
  model_form_step <- proned ~ covid_period + covid_period:month_scaled
}
two_period_unvar <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(two_period_unvar)
two_period_unvar_sum <- model_summary_table(two_period_unvar)

if (n_hospitals>1) {
  model_form_step <- proned ~ covid_period + covid_period:month_scaled + age_at_admission+ bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio + factor(hospital_id)
} else {
model_form_step <- proned ~ covid_period + covid_period:month_scaled + age_at_admission+ bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio 
}

two_period_multivar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(two_period_multivar_mod)
two_period_multivar_sum <- model_summary_table(two_period_multivar_mod)

two_period_table <- rowbind(two_period_unvar_sum, data.frame('site'=c('','Adjusted Model')), fill = TRUE) |>
               rbind(two_period_multivar_sum)
# Write the table to a CSV file
write.csv(two_period_table, paste0(project_location, '/project_output/', site, 'two_period_models_alltime.csv'))


} else { 
#First Univariable
if (n_hospitals>1) {
model_form_step <- proned ~ month_scaled + factor(hospital_id)
} else {
  model_form_step <- proned ~ month_scaled
}
two_period_unvar <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(two_period_unvar)
two_period_unvar_sum <- model_summary_table(two_period_unvar)

#Now Multivariable
if (n_hospitals>1) {
model_form_step <- proned ~ month_scaled + age_at_admission  + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio + factor(hospital_id)
} else {
  model_form_step <- proned ~ month_scaled + age_at_admission  + bmi + factor(max_norepi_equivalent) + or_before_enrollment + min_pf_ratio
}
two_period_multivar_mod <- glm(model_form_step,
          data = prone_analytic_df, 
          family=binomial)
summary(two_period_multivar_mod)
two_period_multivar_sum <- model_summary_table(two_period_multivar_mod)

two_period_table <- rowbind(two_period_unvar_sum, data.frame('site'=c('','Adjusted Model')), fill = TRUE) |>
               rbind(two_period_multivar_sum)
# Write the table to a CSV file
write.csv(two_period_table, paste0(project_location, '/project_output/', site, 'two_period_models_alltime.csv'))
  }

```






```{r Adjusted Analysis Stratified by Hypoxemia Severity}

```

